import { Link } from 'react-router-dom';
import { Layout } from '@/components/Layout';
import { ArrowRight, Sparkles, Brain, Banknote, Cpu, Layers, DollarSign, TrendingUp, Users, Rocket, Compass } from 'lucide-react';
import signatureLines from '@/assets/signature-lines.png';
import norcatHalfLogo from '@/assets/norcat-half-logo.png.asset.json';

const NAVY = '#001A4D';
const BLUE = '#003DA5';
const TEAL = '#00B398';
const PAPER = '#F2F3F6';
const FONT = "'Open Sans', system-ui, sans-serif";

const Eyebrow = ({ children }: { children: React.ReactNode }) => (
  <p className="inline-flex items-center gap-2 text-xs font-semibold tracking-[0.18em] uppercase mb-5"
     style={{ fontFamily: FONT, color: TEAL }}>
    <span className="size-1.5 rounded-full inline-block" style={{ background: TEAL }} />
    {children}
  </p>
);

const Display = ({ children, className = '', as: As = 'h2' as any }: any) => (
  <As className={`font-black uppercase leading-[0.95] tracking-tight text-white ${className}`}
     style={{ fontFamily: FONT, letterSpacing: '-0.02em' }}>
    {children}
  </As>
);

const fundingPrograms = [
  {
    icon: Sparkles,
    name: 'Innovation Acceleration Program',
    tag: 'Non-dilutive',
    description: 'Non-dilutive funding to accelerate market entry for high-growth ventures across Northern Ontario.',
    href: '/funding/innovation-acceleration-program',
  },
  {
    icon: Brain,
    name: 'Regional Artificial Intelligence Program',
    tag: 'AI Ventures',
    description: 'Capital, compute, and support for AI-driven ventures scaling out of Northern Ontario.',
    href: '/funding/regional-ai-program',
  },
  {
    icon: Banknote,
    name: 'Sudbury Catalyst Fund',
    tag: 'Seed Capital',
    description: '$3M early-stage fund co-investing up to $250K alongside qualified angel investors.',
    href: '/funding/sudbury-catalyst-fund',
  },
  {
    icon: Compass,
    name: 'Capital Navigation',
    tag: 'Advisory',
    description: 'Strategic guidance to map, access, and stack the right capital across grants, equity, and debt.',
    href: '/programs/capital-navigation',
  },
];

const impactStats = [
  { number: '$92M', label: 'Capital Invested', sub: 'Deployed across the ecosystem' },
  { number: '187', label: 'Active Companies', sub: 'Funded and supported ventures' },
  { number: '2,000+', label: 'Jobs Created', sub: 'Across Ontario innovation economy' },
  { number: '$48M', label: 'Export Revenue', sub: 'Generated by portfolio ventures' },
];

const Funding = () => {
  return (
    <Layout>
      <div style={{ background: NAVY, color: 'white', fontFamily: FONT }}>

        {/* HERO */}
        <section className="relative overflow-hidden min-h-[70vh] flex items-center pt-8 pb-8 md:pt-12 md:pb-12">
          <div className="absolute inset-0" style={{ background: `linear-gradient(135deg, ${NAVY} 0%, ${BLUE} 50%, ${TEAL} 100%)` }} />
          <div className="absolute inset-0 pointer-events-none bg-center bg-no-repeat bg-cover"
               style={{ backgroundImage: `url(${norcatHalfLogo.url})`, opacity: 0.15 }} />
          <div className="absolute inset-0 pointer-events-none" style={{
            backgroundImage: `radial-gradient(circle at 20% 10%, rgba(0,179,152,0.18), transparent 45%), radial-gradient(circle at 80% 90%, rgba(47,111,214,0.18), transparent 50%)`,
          }} />
          <img src={signatureLines} alt="" aria-hidden="true"
               className="absolute top-0 right-0 w-auto h-1/3 object-contain object-right-top opacity-70 pointer-events-none select-none mix-blend-overlay" />

          <div className="relative mx-auto w-full max-w-7xl px-5 sm:px-6 md:px-10">
            <div className="max-w-3xl xl:max-w-4xl">
              <Eyebrow><DollarSign className="w-3.5 h-3.5" />Capital & Funding Programs</Eyebrow>
              <Display className="text-4xl sm:text-5xl md:text-5xl lg:text-6xl xl:text-[4.5rem]">
                Funding for<br /><span style={{ color: TEAL }}>Northern Innovators.</span>
              </Display>
              <p className="mt-6 md:mt-8 text-base sm:text-lg md:text-xl leading-relaxed max-w-2xl" style={{ color: 'rgba(255,255,255,0.85)' }}>
                Non-dilutive grants, seed capital, and dedicated programs for mining, industrial, and EV ventures scaling out of Ontario. One front door to the region's most active funding streams.
              </p>
              <div className="mt-8 flex flex-wrap gap-3">
                <Link to="/portal/auth"
                      className="inline-flex items-center gap-2 px-6 py-3 rounded-full font-semibold text-sm"
                      style={{ background: TEAL, color: NAVY }}>
                  Become a Client <ArrowRight className="w-4 h-4" />
                </Link>
                <Link to="/programs/capital-navigation"
                      className="inline-flex items-center gap-2 px-6 py-3 rounded-full font-semibold text-sm border border-white/25 text-white hover:bg-white/10">
                  Explore Capital Navigation <Compass className="w-4 h-4" />
                </Link>
              </div>
            </div>
          </div>
        </section>

        {/* PROGRAMS OVERVIEW */}
        <section className="py-20 md:py-28" style={{ background: PAPER, color: NAVY }}>
          <div className="mx-auto w-full max-w-7xl px-5 sm:px-6 md:px-10">
            <div className="max-w-3xl mb-14">
              <p className="text-xs font-semibold tracking-[0.18em] uppercase mb-4" style={{ color: TEAL }}>Funding Programs</p>
              <h2 className="text-3xl md:text-5xl font-black uppercase leading-[0.95]" style={{ letterSpacing: '-0.02em' }}>
                Choose your <span style={{ color: TEAL }}>capital path.</span>
              </h2>
              <p className="mt-5 text-base md:text-lg" style={{ color: 'rgba(0,26,77,0.72)' }}>
                Four flagship pathways designed for different stages, sectors, and outcomes. Each one is a direct link to the team, funding, and support you need.
              </p>
            </div>

            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
              {fundingPrograms.map((p) => (
                <Link key={p.name} to={p.href}
                      className="group relative rounded-2xl p-7 bg-white border border-black/5 hover:border-transparent transition-all hover:-translate-y-1 hover:shadow-xl flex flex-col">
                  <div className="w-12 h-12 rounded-xl flex items-center justify-center mb-5"
                       style={{ background: `${TEAL}15`, color: TEAL }}>
                    <p.icon className="w-6 h-6" />
                  </div>
                  <span className="text-[11px] font-semibold uppercase tracking-wider mb-2" style={{ color: TEAL }}>{p.tag}</span>
                  <h3 className="text-xl font-bold mb-3 leading-tight">{p.name}</h3>
                  <p className="text-sm leading-relaxed mb-6 flex-1" style={{ color: 'rgba(0,26,77,0.72)' }}>{p.description}</p>
                  <span className="inline-flex items-center gap-1.5 text-sm font-semibold" style={{ color: NAVY }}>
                    Learn more <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                  </span>
                </Link>
              ))}
            </div>
          </div>
        </section>


        {/* INDUSTRY TRACK 1: CRITICAL INDUSTRIAL TECHNOLOGIES */}
        <section className="py-20 md:py-28" style={{ background: PAPER, color: NAVY }}>
          <div className="mx-auto w-full max-w-7xl px-5 sm:px-6 md:px-10">
            <div className="max-w-3xl mb-14">
              <p className="text-xs font-semibold tracking-[0.18em] uppercase mb-4" style={{ color: TEAL }}>Industry Track</p>
              <h2 className="text-3xl md:text-5xl font-black uppercase leading-[0.95]" style={{ letterSpacing: '-0.02em' }}>
                Built for <span style={{ color: TEAL }}>Ontario mining.</span>
              </h2>
              <p className="mt-5 text-base md:text-lg" style={{ color: 'rgba(0,26,77,0.72)' }}>
                Critical Industrial Technologies channel funding, facilities, and buyer access to the hard-tech ventures powering Ontario's mining and industrial sectors.
              </p>
            </div>

            <div className="rounded-2xl p-8 bg-white border border-black/5 flex flex-col md:flex-row md:items-center gap-8">
              <div className="flex-1">
                <div className="flex items-start gap-4 mb-5">
                  <div className="w-14 h-14 rounded-xl flex items-center justify-center shrink-0"
                       style={{ background: `linear-gradient(135deg, ${TEAL}20, ${BLUE}10)`, color: TEAL }}>
                    <Cpu className="w-7 h-7" />
                  </div>
                  <div>
                    <h3 className="text-xl md:text-2xl font-bold leading-tight">Critical Industrial Technologies</h3>
                    <p className="text-xs font-semibold uppercase tracking-wider mt-1" style={{ color: TEAL }}>For Ontario mining, industrial, and tough-tech companies</p>
                  </div>
                </div>
                <p className="text-sm md:text-base leading-relaxed mb-5" style={{ color: 'rgba(0,26,77,0.75)' }}>
                  Build, test, and validate hard-tech for the mining and industrial sector with access to funding, facilities, and buyers.
                </p>
                <ul className="space-y-2 mb-6">
                  {['Non-dilutive project funding', 'Real-world testing in the Underground Centre', 'Direct pathways to mining OEMs'].map((b) => (
                    <li key={b} className="flex items-start gap-2 text-sm" style={{ color: 'rgba(0,26,77,0.8)' }}>
                      <span className="mt-1.5 size-1.5 rounded-full shrink-0" style={{ background: TEAL }} />
                      {b}
                    </li>
                  ))}
                </ul>
                <Link to="/mining/critical-industrial-tech"
                      className="inline-flex items-center gap-2 px-5 py-2.5 rounded-full font-semibold text-sm"
                      style={{ background: NAVY, color: 'white' }}>
                  Learn more <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </div>
          </div>
        </section>

        {/* INDUSTRY TRACK 2: CORE5 */}
        <section className="py-20 md:py-28" style={{ background: 'white', color: NAVY }}>
          <div className="mx-auto w-full max-w-7xl px-5 sm:px-6 md:px-10">
            <div className="max-w-3xl mb-14">
              <p className="text-xs font-semibold tracking-[0.18em] uppercase mb-4" style={{ color: TEAL }}>Industry Track</p>
              <h2 className="text-3xl md:text-5xl font-black uppercase leading-[0.95]" style={{ letterSpacing: '-0.02em' }}>
                Built for <span style={{ color: TEAL }}>BEV / EV ventures.</span>
              </h2>
              <p className="mt-5 text-base md:text-lg" style={{ color: 'rgba(0,26,77,0.72)' }}>
                Core5 is the OVIN Northern Regional Technology Development Site supporting SMEs across the full battery and electric vehicle value chain.
              </p>
            </div>

            <div className="rounded-2xl p-8 bg-white border border-black/5 flex flex-col md:flex-row md:items-center gap-8">
              <div className="flex-1">
                <div className="flex items-start gap-4 mb-5">
                  <div className="w-14 h-14 rounded-xl flex items-center justify-center shrink-0"
                       style={{ background: `linear-gradient(135deg, ${TEAL}20, ${BLUE}10)`, color: TEAL }}>
                    <Layers className="w-7 h-7" />
                  </div>
                  <div>
                    <h3 className="text-xl md:text-2xl font-bold leading-tight">Core5</h3>
                    <p className="text-xs font-semibold uppercase tracking-wider mt-1" style={{ color: TEAL }}>For BEV / EV ventures across Northern Ontario</p>
                  </div>
                </div>
                <p className="text-sm md:text-base leading-relaxed mb-5" style={{ color: 'rgba(0,26,77,0.75)' }}>
                  The OVIN Northern Regional Technology Development Site supporting SMEs across the full EV value chain.
                </p>
                <ul className="space-y-2 mb-6">
                  {['Startup & SME funding support', 'Access to R&D and testing facilities', 'Buyer / builder matchmaking'].map((b) => (
                    <li key={b} className="flex items-start gap-2 text-sm" style={{ color: 'rgba(0,26,77,0.8)' }}>
                      <span className="mt-1.5 size-1.5 rounded-full shrink-0" style={{ background: TEAL }} />
                      {b}
                    </li>
                  ))}
                </ul>
                <Link to="/mining/core5"
                      className="inline-flex items-center gap-2 px-5 py-2.5 rounded-full font-semibold text-sm"
                      style={{ background: NAVY, color: 'white' }}>
                  Learn more <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-20 md:py-28 relative overflow-hidden">
          <div className="absolute inset-0" style={{ background: `linear-gradient(135deg, ${NAVY} 0%, ${BLUE} 60%, ${TEAL} 100%)` }} />
          <div className="absolute inset-0 pointer-events-none" style={{
            backgroundImage: `radial-gradient(circle at 30% 40%, rgba(0,179,152,0.28), transparent 45%)`,
          }} />
          <div className="relative mx-auto w-full max-w-5xl px-5 sm:px-6 md:px-10 text-center">
            <Eyebrow><Rocket className="w-3.5 h-3.5" />Ready to raise?</Eyebrow>
            <Display className="text-3xl md:text-5xl lg:text-6xl">
              Let's find your <span style={{ color: TEAL }}>capital fit.</span>
            </Display>
            <p className="mt-6 text-base md:text-lg max-w-2xl mx-auto" style={{ color: 'rgba(255,255,255,0.85)' }}>
              Become a client to unlock program eligibility, or work directly with our Capital Navigation team to map your funding path.
            </p>
            <div className="mt-8 flex flex-wrap gap-3 justify-center">
              <Link to="/portal/auth"
                    className="inline-flex items-center gap-2 px-6 py-3 rounded-full font-semibold text-sm"
                    style={{ background: TEAL, color: NAVY }}>
                Become a Client <ArrowRight className="w-4 h-4" />
              </Link>
              <Link to="/programs/capital-navigation"
                    className="inline-flex items-center gap-2 px-6 py-3 rounded-full font-semibold text-sm border border-white/30 text-white hover:bg-white/10">
                Explore Capital Navigation <Compass className="w-4 h-4" />
              </Link>
            </div>
          </div>
        </section>
      </div>
    </Layout>
  );
};

export default Funding;
